#!/usr/bin/env node

/**
 * Iterative Test Orchestrator - Full Cycles Implementation
 * Runs multiple iterations until 80% coverage and 99% pass rate achieved
 */

const fs = require('fs');
const path = require('path');
const { spawn } = require('child_process');

class IterativeTestOrchestrator {
  constructor() {
    this.maxIterations = 10;
    this.targetCoverage = 80;
    this.targetPassRate = 99;
    this.currentIteration = 0;
    this.iterationResults = [];
    this.outputFile = 'iterative-test-output.txt';
    this.reportFile = 'iterative-test-report.json';
    
    // Clear previous logs
    if (fs.existsSync(this.outputFile)) {
      fs.unlinkSync(this.outputFile);
    }
  }

  log(message) {
    const timestamp = new Date().toISOString();
    const logMessage = `[${timestamp}] ${message}`;
    console.log(logMessage);
    fs.appendFileSync(this.outputFile, logMessage + '\n');
  }

  async runSingleIteration() {
    this.currentIteration++;
    this.log(`🔄 === ITERATION ${this.currentIteration}/${this.maxIterations} ===`);
    
    try {
      // Run the complete test orchestrator
      const result = await this.executeTestOrchestrator();
      
      // Parse results
      const iterationResult = await this.parseIterationResults(result);
      this.iterationResults.push(iterationResult);
      
      this.log(`📊 Iteration ${this.currentIteration} Results:`);
      this.log(`   Coverage: ${iterationResult.coverage.statements}% statements`);
      this.log(`   Pass Rate: ${iterationResult.testResults.passRate}%`);
      this.log(`   Tests: ${iterationResult.testResults.passed}/${iterationResult.testResults.total}`);
      
      return iterationResult;
    } catch (error) {
      this.log(`❌ Iteration ${this.currentIteration} failed: ${error.message}`);
      return null;
    }
  }

  async executeTestOrchestrator() {
    return new Promise((resolve, reject) => {
      const childProcess = spawn('node', ['test-suite/complete_test_orchestrator.js'], {
        cwd: process.cwd(),
        stdio: ['pipe', 'pipe', 'pipe']
      });

      let stdout = '';
      let stderr = '';

      childProcess.stdout.on('data', (data) => {
        const text = data.toString();
        stdout += text;
        // Real-time output
        process.stdout.write(text);
        fs.appendFileSync(this.outputFile, text);
      });

      childProcess.stderr.on('data', (data) => {
        const text = data.toString();
        stderr += text;
        process.stderr.write(text);
        fs.appendFileSync(this.outputFile, text);
      });

      childProcess.on('close', (code) => {
        resolve({ stdout, stderr, exitCode: code });
      });

      childProcess.on('error', (error) => {
        reject(error);
      });

      // Timeout after 15 minutes
      setTimeout(() => {
        childProcess.kill('SIGTERM');
        reject(new Error('Test orchestrator timeout'));
      }, 15 * 60 * 1000);
    });
  }

  async parseIterationResults(result) {
    try {
      // Read the single-run-report.json generated by complete_test_orchestrator
      const reportPath = 'single-run-report.json';
      if (fs.existsSync(reportPath)) {
        const reportData = JSON.parse(fs.readFileSync(reportPath, 'utf8'));
        return {
          iteration: this.currentIteration,
          timestamp: new Date().toISOString(),
          coverage: reportData.coverage,
          testResults: reportData.testResults,
          quality: reportData.quality,
          targetsMet: reportData.targetsMet,
          exitCode: result.exitCode
        };
      } else {
        throw new Error('Single-run report not found');
      }
    } catch (error) {
      this.log(`⚠️ Failed to parse iteration results: ${error.message}`);
      return {
        iteration: this.currentIteration,
        timestamp: new Date().toISOString(),
        coverage: { statements: 0, branches: 0, functions: 0, lines: 0 },
        testResults: { total: 0, passed: 0, failed: 0, passRate: 0 },
        quality: { coverageScore: 0, passRateScore: 0, meetsTargets: false },
        targetsMet: false,
        exitCode: result.exitCode,
        error: error.message
      };
    }
  }

  checkTargetsAchieved(result) {
    if (!result) return false;
    
    const coverageAchieved = result.coverage.statements >= this.targetCoverage;
    const passRateAchieved = result.testResults.passRate >= this.targetPassRate;
    
    return coverageAchieved && passRateAchieved;
  }

  async generateFailureAnalysis() {
    this.log('🔍 Analyzing failure patterns across iterations...');
    
    const analysis = {
      coverageProgression: this.iterationResults.map(r => ({
        iteration: r.iteration,
        statements: r.coverage.statements,
        branches: r.coverage.branches,
        functions: r.coverage.functions,
        lines: r.coverage.lines
      })),
      passRateProgression: this.iterationResults.map(r => ({
        iteration: r.iteration,
        passRate: r.testResults.passRate,
        passed: r.testResults.passed,
        failed: r.testResults.failed,
        total: r.testResults.total
      })),
      commonIssues: this.identifyCommonIssues(),
      recommendations: this.generateRecommendations()
    };

    this.log('📋 Common Issues Identified:');
    analysis.commonIssues.forEach(issue => {
      this.log(`   • ${issue}`);
    });

    this.log('💡 Recommendations:');
    analysis.recommendations.forEach(rec => {
      this.log(`   • ${rec}`);
    });

    return analysis;
  }

  identifyCommonIssues() {
    const issues = [];
    
    // Check for stagnant coverage
    const lastResult = this.iterationResults[this.iterationResults.length - 1];
    if (lastResult && lastResult.coverage.statements < 20) {
      issues.push('Low overall coverage - need more comprehensive test generation');
    }
    
    // Check for network/timeout issues
    const hasNetworkIssues = this.iterationResults.some(r => 
      r.testResults.passRate === 0 && r.testResults.total === 0
    );
    if (hasNetworkIssues) {
      issues.push('Network connectivity issues preventing test execution');
    }

    // Check for timeout issues
    issues.push('Test timeout issues - need to optimize test execution time');
    issues.push('Missing test server setup for API integration tests');
    
    return issues;
  }

  generateRecommendations() {
    return [
      'Implement mock servers for API tests to avoid network dependencies',
      'Reduce test timeout values and optimize test execution',
      'Generate more unit tests for uncovered functions and branches',
      'Fix existing test failures before generating new tests',
      'Implement test server setup/teardown for integration tests',
      'Add more edge case testing for better branch coverage'
    ];
  }

  async generateFinalReport() {
    const finalReport = {
      summary: {
        totalIterations: this.currentIteration,
        maxIterations: this.maxIterations,
        targetCoverage: this.targetCoverage,
        targetPassRate: this.targetPassRate,
        finalResult: this.iterationResults[this.iterationResults.length - 1],
        targetsAchieved: this.checkTargetsAchieved(this.iterationResults[this.iterationResults.length - 1])
      },
      iterations: this.iterationResults,
      analysis: await this.generateFailureAnalysis(),
      timestamp: new Date().toISOString()
    };

    fs.writeFileSync(this.reportFile, JSON.stringify(finalReport, null, 2));
    
    this.log('📄 Final Report Generated:');
    this.log(`   File: ${this.reportFile}`);
    this.log(`   Iterations: ${finalReport.summary.totalIterations}`);
    this.log(`   Targets Achieved: ${finalReport.summary.targetsAchieved ? 'YES' : 'NO'}`);
    
    if (finalReport.summary.finalResult) {
      this.log(`   Final Coverage: ${finalReport.summary.finalResult.coverage.statements}%`);
      this.log(`   Final Pass Rate: ${finalReport.summary.finalResult.testResults.passRate}%`);
    }

    return finalReport;
  }

  async run() {
    this.log('🚀 Starting Iterative Test Orchestrator');
    this.log(`🎯 Targets: ${this.targetCoverage}% coverage, ${this.targetPassRate}% pass rate`);
    this.log(`📊 Max iterations: ${this.maxIterations}`);
    
    let targetsAchieved = false;
    
    while (this.currentIteration < this.maxIterations && !targetsAchieved) {
      const result = await this.runSingleIteration();
      
      if (result) {
        targetsAchieved = this.checkTargetsAchieved(result);
        
        if (targetsAchieved) {
          this.log('🎉 TARGETS ACHIEVED!');
          this.log(`✅ Coverage: ${result.coverage.statements}% >= ${this.targetCoverage}%`);
          this.log(`✅ Pass Rate: ${result.testResults.passRate}% >= ${this.targetPassRate}%`);
          break;
        }
      }
      
      if (this.currentIteration < this.maxIterations) {
        this.log(`⏳ Preparing for next iteration...`);
        await new Promise(resolve => setTimeout(resolve, 5000)); // 5 second pause
      }
    }
    
    if (!targetsAchieved) {
      this.log('⚠️ Maximum iterations reached without achieving targets');
    }
    
    const finalReport = await this.generateFinalReport();
    
    this.log('🏁 Iterative Test Orchestrator Complete');
    return finalReport;
  }
}

// Main execution
async function main() {
  const orchestrator = new IterativeTestOrchestrator();
  
  try {
    const report = await orchestrator.run();
    process.exit(report.summary.targetsAchieved ? 0 : 1);
  } catch (error) {
    console.error('❌ Iterative orchestrator failed:', error.message);
    process.exit(1);
  }
}

if (require.main === module) {
  main();
}

module.exports = IterativeTestOrchestrator;
