global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - "alert_rules.yml"

scrape_configs:
  # Scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Scrape Node Exporter metrics (system metrics)
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]

  # Scrape Chatbots API metrics
  - job_name: "chatbots-api"
    metrics_path: /api/v1/metrics
    scrape_interval: 10s
    static_configs:
      - targets: ["app:3000"]
    
  # Scrape MongoDB metrics
  - job_name: "mongodb"
    static_configs:
      - targets: ["mongodb-exporter:9216"]

  # Scrape Redis metrics
  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]

  # Scrape Nginx metrics
  - job_name: "nginx"
    static_configs:
      - targets: ["nginx-exporter:9113"]

  # Scrape Docker metrics
  - job_name: "docker"
    static_configs:
      - targets: ["cadvisor:8080"]
