global:
  resolve_timeout: 5m
  slack_api_url: 'https://hooks.slack.com/services/XXXXXXXXX/XXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXX'

route:
  group_by: ['alertname', 'job', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'slack-notifications'
  routes:
  - match:
      severity: critical
    receiver: 'slack-critical'
    continue: true
  - match:
      severity: warning
    receiver: 'slack-warnings'
    continue: true
  - match_re:
      service: ^(chatbot-platform|database)$
    receiver: 'team-chatbot'
    continue: true
  - match:
      deployment: 'true'
    receiver: 'deployment-team'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#monitoring'
    send_resolved: true
    title: '[{{ .Status | toUpper }}] {{ .CommonLabels.alertname }}'
    text: >-
      {{ range .Alerts }}
        *Alert:* {{ .Annotations.summary }}
        *Description:* {{ .Annotations.description }}
        *Severity:* {{ .Labels.severity }}
        *Started:* {{ .StartsAt.Format "2006-01-02 15:04:05" }}
      {{ end }}

- name: 'slack-critical'
  slack_configs:
  - channel: '#critical-alerts'
    send_resolved: true
    title: '[CRITICAL] {{ .CommonLabels.alertname }}'
    text: >-
      {{ range .Alerts }}
        *Alert:* {{ .Annotations.summary }}
        *Description:* {{ .Annotations.description }}
        *Severity:* {{ .Labels.severity }}
        *Started:* {{ .StartsAt.Format "2006-01-02 15:04:05" }}
      {{ end }}

- name: 'slack-warnings'
  slack_configs:
  - channel: '#warning-alerts'
    send_resolved: true
    title: '[WARNING] {{ .CommonLabels.alertname }}'
    text: >-
      {{ range .Alerts }}
        *Alert:* {{ .Annotations.summary }}
        *Description:* {{ .Annotations.description }}
        *Severity:* {{ .Labels.severity }}
        *Started:* {{ .StartsAt.Format "2006-01-02 15:04:05" }}
      {{ end }}

- name: 'team-chatbot'
  slack_configs:
  - channel: '#team-chatbot'
    send_resolved: true
    title: '[{{ .Status | toUpper }}] {{ .CommonLabels.alertname }}'
    text: >-
      {{ range .Alerts }}
        *Alert:* {{ .Annotations.summary }}
        *Description:* {{ .Annotations.description }}
        *Severity:* {{ .Labels.severity }}
        *Started:* {{ .StartsAt.Format "2006-01-02 15:04:05" }}
      {{ end }}

- name: 'deployment-team'
  slack_configs:
  - channel: '#deployments'
    send_resolved: true
    title: '[DEPLOYMENT] {{ .CommonLabels.alertname }}'
    text: >-
      {{ range .Alerts }}
        *Alert:* {{ .Annotations.summary }}
        *Description:* {{ .Annotations.description }}
        *Severity:* {{ .Labels.severity }}
        *Started:* {{ .StartsAt.Format "2006-01-02 15:04:05" }}
      {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'job']
