global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - "alerts/*.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "chatbot-platform"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["chatbot-platform:3000"]
    
  - job_name: "chatbot-platform-blue"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["chatbot-platform-blue:3000"]
    
  - job_name: "chatbot-platform-green"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["chatbot-platform-green:3000"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "mongodb-exporter"
    static_configs:
      - targets: ["mongodb-exporter:9216"]
