apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chatbots-platform.fullname" . }}-secrets
  labels:
    {{- include "chatbots-platform.labels" . | nindent 4 }}
type: Opaque
data:
  mongodb-uri: {{ .Values.config.mongodb.uri | b64enc | quote }}
  jwt-secret: {{ .Values.config.jwt.secret | b64enc | quote }}
  refresh-token-secret: {{ .Values.config.refreshToken.secret | b64enc | quote }}
