apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-platform-blue
  namespace: chatbot-platform-prod
  labels:
    app: chatbot-platform
    color: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chatbot-platform
      color: blue
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: chatbot-platform
        color: blue
    spec:
      containers:
      - name: chatbot-platform
        image: ghcr.io/qaaph-zyld/chatbots:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: DEPLOYMENT_COLOR
          value: "blue"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: chatbot-platform-secrets
              key: database-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: chatbot-platform-secrets
              key: jwt-secret
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: chatbot-platform-secrets
              key: stripe-secret-key
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      imagePullSecrets:
      - name: github-container-registry
