apiVersion: v2
name: chatbots-platform
description: A Helm chart for the Chatbots Platform
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - chatbot
  - nlp
  - ai
maintainers:
  - name: Chatbots Platform Team
    email: team@example.com
dependencies:
  - name: mongodb
    version: "12.1.31"
    repository: "https://charts.bitnami.com/bitnami"
    condition: dependencies.mongodb.enabled
  - name: redis
    version: "17.3.14"
    repository: "https://charts.bitnami.com/bitnami"
    condition: dependencies.redis.enabled
